### PR TITLE
added touch support to v2.0.0

### PR DESCRIPTION
**Pull request by andrewgaun**
#24

### CODE REVIEW

**Comment by Fuzzyma** [comment]
man this is beautiful!
I would say since this is a feature it should be version 2.1.0 instead of 2.0.1.
If you dont intend to change this I will merge it after your okay.

**Comment by andrewgaun** [comment]
updated the version to 2.1.0.

**Comment by Fuzzyma** [comment]
Thank you :)

**Comment by Fuzzyma** [comment]
You had a typo in your PR (`event` instead of `e`). I wonder how they all can say that it is working ^^

**Comment by Fuzzyma** [comment]
Another qustion: I wonder why you added the `event || window.event` since we dont need to support IE 8 anymore. Has it something to do with these touch devices?

**Pull request merged**
