### PR TITLE
Enhancement Request - Add touch events #24

### PR DESCRIPTION
**Pull request by raks437**
Enhancement Request - Added touch events #24 
added a hack for iPad

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Are you willing to implement that for the new version again?

**Comment by raks437** [comment]
Sure. My work schedule is little packed up, but I'll note this as my 1st #todo as soon I can.

**Comment by Fuzzyma** [comment]
ping :)

**Comment by bubenshchykov** [comment]
+1 ping! :)

**Comment by bubenshchykov** [comment]
that's fixed in master now :)
https://github.com/wout/svg.draggable.js/commit/00e68cd3ebeeea6a10f767ec190cfffc82ba270e
web,android,iphone,ipad tested

**Pull request closed without merging**
