### PR TITLE
Fixed errors, updated callback handling

### PR DESCRIPTION
**Pull request by FlorianLoch**
Updated the callback handling; before the delta object given to the callbacks just ignored that the element itself might not have been moved do to constraints (object or newly implemented function), it just contained information about where the element would be without constraints.
This pull request should fix all other errors too.
I also updated the README according to callback handling.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Are you willing to implement that in the new version again?

**Comment by FlorianLoch** [comment]
Hi,
sorry for replying that late… I am very busy at the moment. I will have a look at the code at the weekend.

Best regards
Florian 

--
Florian Loch
florian.loch@gmail.com <mailto:florian.loch@gmail.com>
Mobil: +4917691354966
Tennesseeallee 28
76149 Karlsruhe

**Comment by FlorianLoch** [comment]
Ok, so it seems like you already implemented it quite nicely. So we can finally close this request?

**Comment by Fuzzyma** [comment]
Did I? I thought your code will do something more which I missed in my code

**Comment by FlorianLoch** [comment]
I am pretty sure you did - I checked both versions and the features I added are implemented in the new version too. :+1:

**Comment by Fuzzyma** [comment]
Than it was something already implemented before I started working on it :)
Thank you anyway!

**Pull request closed without merging**
