### PR TITLE
PR - add event when draggable el is moved // solved two finger touch problem

### PR DESCRIPTION
**Pull request by radabass**
Includes two commits:
The first commit adds a new event called 'draggable' triggered only if the draggable element has been moved onto a new position, it includes the delta of the movement just in case an external script requires it.
The second commit prevents the dragged element to become unstable once a user touches on a screen with two fingers, in that case the event off is never reached for one of the events.

### CODE REVIEW

**Comment by radabass** [comment]
Hi, it's just for simplicity, on the other hand the other way to do it in external code will be something like this:
```javascript
var isElementStill;
svgGroup.on('dragstart', function(){isElementStill = true;});
svgGroup.on('dragmove', function(ev){
	var handler = ev.detail.handler,
		p = handler.transformPoint(ev.detail.event);
	if(handler.startPoints.point.x !== p.x || handler.startPoints.point.y !== p.y){
		isElementStill = false;
	}
});
```

And on dragend or mouseup <code>isElementStill</code> will mark if the element is moved while dragging.

Correct me if I'm wrong.

Thank you.

**Comment by Fuzzyma** [comment]
why you need this variable `isElementStill`? You can just check there if it moved and do what you want after. Additionally there is a property `p` in the details-object. You dont have to transform it yourself.
The code then would transform to:

```
svgGroup.on('dragmove', function(ev){
    var data = ev.detail
    if(data.handler.startPoints.point.x === data.p.x && datahandler.startPoints.point.y === data.p.y){
        // do nothing
        return
    }

    // do whatever you like when the element moved
});

The new event would serve as shortcut for a feature which is only needed in certain edge cases.
Thats why I wont include that in the plugin. Its actually not that much code you have to write for that so it should be fine.

However the other commit seems interesting but I dont like how it is solved. It would be better to check if the element is already dragged and just ignore the second touch

**Comment by radabass** [comment]
I agree with you about the second commit, if the element is currently dragged avoid a second touch is the way to go.

Eventually this is the code for the movement detection if its useful for anybody:

```javascript
svgGroup.on('dragend', function(ev){
	var handler = ev.detail.handler,
		p = handler.transformPoint(ev.detail.event);
	if(handler.startPoints.point.x !== p.x || handler.startPoints.point.y !== p.y){
		// the code if element is moved
	}
});
```
(the svgGroup is previously scaled, btw)

**Comment by Fuzzyma** [comment]
I still dont know why you transform the point. Its already given to you in `ev.detail.p`

**Comment by radabass** [comment]
So in a click event (without drag movement) ev.detail.p must be equal to ev.detail.handler.startPoints.point?

**Comment by Fuzzyma** [comment]
You just found a bug ;). will fix it - thank you!

**Comment by Fuzzyma** [comment]
Maybe you can try it again? :)

**Comment by radabass** [comment]
Now it works as expected ;-)

```javascript
svgGroup.on('dragend', function(ev){
    var handler = ev.detail.handler,
        p = ev.detail.p;
    if(handler.startPoints.point.x !== p.x || handler.startPoints.point.y !== p.y){
        // the code if element is moved
    }
});
```
Thank you

**Comment by radabass** [comment]
Hi again and thank you for your time, may you please check [3caaa83](https://github.com/radabass/svg.draggable.js/commit/3caaa833f61684ea744b4944a7c67b4050a1e3a0) it is an idea to prevent multitouch events, I'm sure the coding may be way better but meanwhile it seems to work.

**Pull request closed without merging**
