### PR TITLE
make it browserifiable

### PR DESCRIPTION
**Pull request by fibo**
First of all, thank you for svg.js! It is the best choice I found for SVG. I am using it for my Dataflow programming engine [dflow](http://g14n.info), and, as soon as I will have any kind of income I will contribute back to svg.js (by now I am my only user :). 

I did this modification to be able to create a browserify bundle of svg.js + plugins. By now I am using only *svg.draggable.js* and I would like to discuss this methos, and possibly apply to other plugins I would like to use: next I will target is *svg.foreignobject.js*.
 
About the modification, I just added a *main* attribute to the package.json in order to be able to require this package and browserify it.

See my [extended svg.js](https://github.com/fibo/flow-view/blob/master/src/SVG.js) for a working example.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Looks like I missed that :)

**Comment by fibo** [comment]
I also forked your version of svg.foreignobject.js; if it is ok for you I would like to publish it on npm.

**Comment by Fuzzyma** [comment]
Please dont publish a fork on npm since. This version will be on npm as soon as I can rework it. You would steal the namespace!
You maybe know that svg.js v2 was released last week and I have to review all plugins for that which needs some time. But when I am done all plugins will be available via npm

**Comment by fibo** [comment]
No prob. I have no hurry. I will send you a pull request.

**Pull request merged**
